name: sample action
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  job1:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: print
        run:  |
          pwd
          ls -la
          git branch
          cat README.md
   
